import { FormBuilder, FormGroup } from '@angular/forms';
import { NavController, ModalController, AlertController, NavParams, Platform } from 'ionic-angular';
import { Keyboard } from '@ionic-native/keyboard';
import { Clinical6Service } from '../../clinical6.service';
import { AppConfig } from '../../config';
import { TranslatorService } from '../../translator/translator.service';
import { AppLoginService } from '../../login.service';
import { NativePageTransitions, NativeTransitionOptions } from '@ionic-native/native-page-transitions';
export declare class LoginWithPinPage {
    appConfig: AppConfig;
    loginSvc: AppLoginService;
    translatorService: TranslatorService;
    nav: NavController;
    navParams: NavParams;
    captiveReach: Clinical6Service;
    modalCtrl: ModalController;
    alertCtrl: AlertController;
    formBuilder: FormBuilder;
    keyboard: Keyboard;
    platform: Platform;
    nativePageTransitions: NativePageTransitions;
    authForm: FormGroup;
    pin: string;
    email: string;
    code: string;
    newPin: string;
    newPinConfirm: string;
    showPinPage: boolean;
    showEmailPage: boolean;
    showForgotPasswordPage: boolean;
    showActivationCodePage: boolean;
    showResetPinPage: boolean;
    isNavigating: boolean;
    focusOut: boolean;
    countAlert: number;
    failedLogins: number;
    skipActivationCode: boolean;
    _title: string;
    _resetPINText: string;
    backTransition: NativeTransitionOptions;
    nextTransition: NativeTransitionOptions;
    showBackButton: boolean;
    constructor(appConfig: AppConfig, loginSvc: AppLoginService, translatorService: TranslatorService, nav: NavController, navParams: NavParams, captiveReach: Clinical6Service, modalCtrl: ModalController, alertCtrl: AlertController, formBuilder: FormBuilder, keyboard: Keyboard, platform: Platform, nativePageTransitions: NativePageTransitions);
    ngOnInit(): void;
    ionWillEnter(): void;
    keyboardPin(event: KeyboardEvent): void;
    title: string;
    resetPINText: string;
    goBackPop(): void;
    goNext(): Promise<any>;
    goBackTransition(): Promise<any>;
    goBack(): Promise<void>;
    login(): Promise<boolean>;
    showLoginError(): void;
    passwordResetSuccess(): void;
    loginSuccess(): Promise<void>;
    resetPin(): Promise<void>;
    send(): Promise<void>;
    continue(): Promise<void>;
    activation(): Promise<void>;
    submit(): Promise<void>;
    showCreatePinError(data: any): void;
    goToEmailPage(): Promise<void>;
    showAlert(title: string, message: string): void;
    showError(errorSubTitle: string, errorText: string): void;
    translate(string_key: any): string;
}
