import { NavController, ModalController, AlertController, NavParams, Loading, LoadingController } from 'ionic-angular';
import { Clinical6Service } from '../../clinical6.service';
import { FormBuilder, FormGroup } from '@angular/forms';
import { Keyboard } from '@ionic-native/keyboard';
import { AppConfig } from '../../config/app.config';
import { TranslatorService } from '../../translator/translator.service';
import { AppLoginService } from '../../login.service';
export declare class PinPage {
    loadingController: LoadingController;
    appConfig: AppConfig;
    loginSvc: AppLoginService;
    translatorService: TranslatorService;
    nav: NavController;
    navParams: NavParams;
    captiveReach: Clinical6Service;
    modalCtrl: ModalController;
    alertCtrl: AlertController;
    formBuilder: FormBuilder;
    keyboard: Keyboard;
    apiBaseUrl: string;
    authForm: FormGroup;
    pin: string;
    pinConfirm: string;
    isNavigating: boolean;
    nextFlow: boolean;
    focusOut: boolean;
    loading: Loading;
    _title: string;
    _pinLabel: string;
    _pinConfirmationLabel: string;
    _helpText: string;
    _pinError: string;
    _unlockMessage: string;
    constructor(loadingController: LoadingController, appConfig: AppConfig, loginSvc: AppLoginService, translatorService: TranslatorService, nav: NavController, navParams: NavParams, captiveReach: Clinical6Service, modalCtrl: ModalController, alertCtrl: AlertController, formBuilder: FormBuilder, keyboard: Keyboard);
    ngOnInit(): void;
    ionViewWillEnter(): void;
    ionViewDidLeave(): void;
    unlock(): void;
    unlockOld(): void;
    goBack(): void;
    moveToNextFlow(): void;
    showError(errorSubTitle: string, errorText: string): void;
    showAlert(title: string, message: string): void;
    title: string;
    pinLabel: string;
    pinConfirmationLabel: string;
    helpText: string;
    pinError: string;
    unlockMessage: string;
    translate(string_key: string): string;
    presentLoading(): void;
}
