
export const COUNTRIES =  [
    { id: 'Afghanistan', body: 'Afghanistan'},
    { id: 'Albania', body: 'Albania'},
    { id: 'Algeria', body: 'Algeria'},
    { id: 'Andorra', body: 'Andorra'},
    { id: 'Angola', body: 'Angola'} ,
    { id: 'Antigua & Deps', body: 'Antigua & Deps'} ,
    { id: 'Argentina', body: 'Argentina'} ,
    { id: 'Armenia', body: 'Armenia'} ,
    { id: 'Australia', body: 'Australia'} ,
    { id: 'Austria', body: 'Austria'} ,
    { id: 'Azerbaijan', body: 'Azerbaijan'} ,
    { id: 'Bahamas', body: 'Bahamas'} ,
    { id: 'Bahrain', body: 'Bahrain'} ,
    { id: 'Bangladesh', body: 'Bangladesh'} ,
    { id: 'Barbados', body: 'Barbados'} ,
    { id: 'Belarus', body: 'Belarus'} ,
    { id: 'Belgium', body: 'Belgium'} ,
    { id: 'Belize', body: 'Belize'} ,
    { id: 'Benin', body: 'Benin'} ,
    { id: 'Bhutan', body: 'Bhutan'} ,
    { id: 'Bolivia', body: 'Bolivia'} ,
    { id: 'Bosnia Herzegovina', body: 'Bosnia Herzegovina'} ,
    { id: 'Botswana', body: 'Botswana'} ,
    { id: 'Brazil', body: 'Brazil'} ,
    { id: 'Brunei', body: 'Brunei'} ,
    { id: 'Bulgaria', body: 'Bulgaria'} ,
    { id: 'Burkina', body: 'Burkina'} ,
    { id: 'Burundi', body: 'Burundi'} ,
    { id: 'Cambodia', body: 'Cambodia'} ,
    { id: 'Cameroon', body: 'Cameroon'} ,
    { id: 'Canada', body: 'Canada'} ,
    { id: 'Cape Verde', body: 'Cape Verde'} ,
    { id: 'Central African Rep', body: 'Central African Rep'} ,
    { id: 'Chad', body: 'Chad'} ,
    { id: 'Chile', body: 'Chile'} ,
    { id: 'China', body: 'China'} ,
    { id: 'Colombia', body: 'Colombia'} ,
    { id: 'Comoros', body: 'Comoros'} ,
    { id: 'Congo', body: 'Congo'} ,
    { id: 'Congo', body: 'Congo'} ,
    { id: 'Costa Rica', body: 'Costa Rica'} ,
    { id: 'Croatia', body: 'Croatia'} ,
    { id: 'Cuba', body: 'Cuba'} ,
    { id: 'Cyprus', body: 'Cyprus'} ,
    { id: 'Czech Republic', body: 'Czech Republic'} ,
    { id: 'Denmark', body: 'Denmark'} ,
    { id: 'Djibouti', body: 'Djibouti'} ,
    { id: 'Dominica', body: 'Dominica'} ,
    { id: 'Dominican Republic', body: 'Dominican Republic'} ,
    { id: 'East Timor', body: 'East Timor'} ,
    { id: 'Ecuador', body: 'Ecuador'} ,
    { id: 'Egypt', body: 'Egypt'} ,
    { id: 'El Salvador', body: 'El Salvador'} ,
    { id: 'Equatorial Guinea', body: 'Equatorial Guinea'} ,
    { id: 'Eritrea', body: 'Eritrea'} ,
    { id: 'Estonia', body: 'Estonia'} ,
    { id: 'Ethiopia', body: 'Ethiopia'} ,
    { id: 'Fiji', body: 'Fiji'} ,
    { id: 'Finland', body: 'Finland'} ,
    { id: 'France', body: 'France'} ,
    { id: 'Gabon', body: 'Gabon'} ,
    { id: 'Gambia', body: 'Gambia'} ,
    { id: 'Georgia', body: 'Georgia'} ,
    { id: 'Germany', body: 'Germany'} ,
    { id: 'Ghana', body: 'Ghana'} ,
    { id: 'Greece', body: 'Greece'} ,
    { id: 'Grenada', body: 'Grenada'} ,
    { id: 'Guatemala', body: 'Guatemala'} ,
    { id: 'Guinea', body: 'Guinea'} ,
    { id: 'Guinea-Bissau', body: 'Guinea-Bissau'} ,
    { id: 'Guyana', body: 'Guyana'} ,
    { id: 'Haiti', body: 'Haiti'} ,
    { id: 'Honduras', body: 'Honduras'} ,
    { id: 'Hungary', body: 'Hungary'} ,
    { id: 'Iceland', body: 'Iceland'} ,
    { id: 'India', body: 'India'} ,
    { id: 'Indonesia', body: 'Indonesia'} ,
    { id: 'Iran', body: 'Iran'} ,
    { id: 'Iraq', body: 'Iraq'} ,
    { id: 'Ireland', body: 'Ireland'} ,
    { id: 'Israel', body: 'Israel'} ,
    { id: 'Italy', body: 'Italy'} ,
    { id: 'Ivory Coast', body: 'Ivory Coast'} ,
    { id: 'Jamaica', body: 'Jamaica'} ,
    { id: 'Japan', body: 'Japan'} ,
    { id: 'Jordan', body: 'Jordan'} ,
    { id: 'Kazakhstan', body: 'Kazakhstan'} ,
    { id: 'Kenya', body: 'Kenya'} ,
    { id: 'Kiribati', body: 'Kiribati'} ,
    { id: 'Korea North', body: 'Korea North'} ,
    { id: 'Korea South', body: 'Korea South'} ,
    { id: 'Kosovo', body: 'Kosovo'} ,
    { id: 'Kuwait', body: 'Kuwait'} ,
    { id: 'Kyrgyzstan', body: 'Kyrgyzstan'} ,
    { id: 'Laos', body: 'Laos'} ,
    { id: 'Latvia', body: 'Latvia'} ,
    { id: 'Lebanon', body: 'Lebanon'} ,
    { id: 'Lesotho', body: 'Lesotho'} ,
    { id: 'Liberia', body: 'Liberia'} ,
    { id: 'Libya', body: 'Libya'} ,
    { id: 'Liechtenstein', body: 'Liechtenstein'} ,
    { id: 'Lithuania', body: 'Lithuania'} ,
    { id: 'Luxembourg', body: 'Luxembourg'} ,
    { id: 'Macedonia', body: 'Macedonia'} ,
    { id: 'Madagascar', body: 'Madagascar'} ,
    { id: 'Malawi', body: 'Malawi'} ,
    { id: 'Malaysia', body: 'Malaysia'} ,
    { id: 'Maldives', body: 'Maldives'} ,
    { id: 'Mali', body: 'Mali'} ,
    { id: 'Malta', body: 'Malta'} ,
    { id: 'Marshall Islands', body: 'Marshall Islands'} ,
    { id: 'Mauritania', body: 'Mauritania'} ,
    { id: 'Mauritius', body: 'Mauritius'} ,
    { id: 'Mexico', body: 'Mexico'} ,
    { id: 'Micronesia', body: 'Micronesia'} ,
    { id: 'Moldova', body: 'Moldova'} ,
    { id: 'Monaco', body: 'Monaco'} ,
    { id: 'Mongolia', body: 'Mongolia'} ,
    { id: 'Montenegro', body: 'Montenegro'} ,
    { id: 'Morocco', body: 'Morocco'} ,
    { id: 'Mozambique', body: 'Mozambique'} ,
    { id: 'Myanmar, {Burma}', body: 'Myanmar, {Burma}'} ,
    { id: 'Namibia', body: 'Namibia'} ,
    { id: 'Nauru', body: 'Nauru'} ,
    { id: 'Nepal', body: 'Nepal'} ,
    { id: 'Netherlands', body: 'Netherlands'} ,
    { id: 'New Zealand', body: 'New Zealand'} ,
    { id: 'Nicaragua', body: 'Nicaragua'} ,
    { id: 'Niger', body: 'Niger'} ,
    { id: 'Nigeria', body: 'Nigeria'} ,
    { id: 'Norway', body: 'Norway'} ,
    { id: 'Oman', body: 'Oman'} ,
    { id: 'Pakistan', body: 'Pakistan'} ,
    { id: 'Palau', body: 'Palau'} ,
    { id: 'Panama', body: 'Panama'} ,
    { id: 'Papua New Guinea', body: 'Papua New Guinea'} ,
    { id: 'Paraguay', body: 'Paraguay'} ,
    { id: 'Peru', body: 'Peru'} ,
    { id: 'Philippines', body: 'Philippines'} ,
    { id: 'Poland', body: 'Poland'} ,
    { id: 'Portugal', body: 'Portugal'} ,
    { id: 'Qatar', body: 'Qatar'} ,
    { id: 'Romania', body: 'Romania'} ,
    { id: 'Russian Federation', body: 'Russian Federation'} ,
    { id: 'Rwanda', body: 'Rwanda'} ,
    { id: 'St Kitts & Nevis', body: 'St Kitts & Nevis'} ,
    { id: 'St Lucia', body: 'St Lucia'} ,
    { id: 'Saint Vincent & the Grenadines', body: 'Saint Vincent & the Grenadines'} ,
    { id: 'Samoa', body: 'Samoa'} ,
    { id: 'San Marino', body: 'San Marino'} ,
    { id: 'Sao Tome & Principe', body: 'Sao Tome & Principe'} ,
    { id: 'Saudi Arabia', body: 'Saudi Arabia'} ,
    { id: 'Senegal', body: 'Senegal'} ,
    { id: 'Serbia', body: 'Serbia'} ,
    { id: 'Seychelles', body: 'Seychelles'} ,
    { id: 'Sierra Leone', body: 'Sierra Leone'} ,
    { id: 'Singapore', body: 'Singapore'} ,
    { id: 'Slovakia', body: 'Slovakia'} ,
    { id: 'Slovenia', body: 'Slovenia'} ,
    { id: 'Solomon Islands', body: 'Solomon Islands'} ,
    { id: 'Somalia', body: 'Somalia'} ,
    { id: 'South Africa', body: 'South Africa'} ,
    { id: 'South Sudan', body: 'South Sudan'} ,
    { id: 'Spain', body: 'Spain'} ,
    { id: 'Sri Lanka', body: 'Sri Lanka'} ,
    { id: 'Sudan', body: 'Sudan'} ,
    { id: 'Suriname', body: 'Suriname'} ,
    { id: 'Swaziland', body: 'Swaziland'} ,
    { id: 'Sweden', body: 'Sweden'} ,
    { id: 'Switzerland', body: 'Switzerland'} ,
    { id: 'Syria', body: 'Syria'} ,
    { id: 'Taiwan', body: 'Taiwan'} ,
    { id: 'Tajikistan', body: 'Tajikistan'} ,
    { id: 'Tanzania', body: 'Tanzania'} ,
    { id: 'Thailand', body: 'Thailand'} ,
    { id: 'Togo', body: 'Togo'} ,
    { id: 'Tonga', body: 'Tonga'} ,
    { id: 'Trinidad & Tobago', body: 'Trinidad & Tobago'} ,
    { id: 'Tunisia', body: 'Tunisia'} ,
    { id: 'Turkey', body: 'Turkey'} ,
    { id: 'Turkmenistan', body: 'Turkmenistan'} ,
    { id: 'Tuvalu', body: 'Tuvalu'} ,
    { id: 'Uganda', body: 'Uganda'} ,
    { id: 'Ukraine', body: 'Ukraine'} ,
    { id: 'United Arab Emirates', body: 'United Arab Emirates'} ,
    { id: 'United Kingdom', body: 'United Kingdom'} ,
    { id: 'United States', body: 'United States'} ,
    { id: 'Uruguay', body: 'Uruguay'} ,
    { id: 'Uzbekistan', body: 'Uzbekistan'} ,
    { id: 'Vanuatu', body: 'Vanuatu'} ,
    { id: 'Vatican City', body: 'Vatican City'} ,
    { id: 'Venezuela', body: 'Venezuela'} ,
    { id: 'Vietnam', body: 'Vietnam'} ,
    { id: 'Yemen', body: 'Yemen'} ,
    { id: 'Zambia', body: 'Zambia'} ,
    { id: 'Zimbabwe', body: 'Zimbabwe'}
];
export const STATE =   [
    { id: 'Alabama', body: 'Alabama'} ,
    { id: 'Alaska', body: 'Alaska'} ,
    { id: 'Arizona', body: 'Arizona'} ,
    { id: 'Arkansas', body: 'Arkansas'} ,
    { id: 'California', body: 'California'} ,
    { id: 'Colorado', body: 'Colorado'} ,
    { id: 'Connecticut', body: 'Connecticut'} ,
    { id: 'Delaware', body: 'Delaware'} ,
    { id: 'Florida', body: 'Florida'} ,
    { id: 'Georgia', body: 'Georgia'} ,
    { id: 'Hawaii', body: 'Hawaii'} ,
    { id: 'Idaho', body: 'Idaho'} ,
    { id: 'Illinois', body: 'Illinois'} ,
    { id: 'Indiana', body: 'Indiana'} ,
    { id: 'Iowa', body: 'Iowa'} ,
    { id: 'Kansas', body: 'Kansas'} ,
    { id: 'Kentucky', body: 'Kentucky'} ,
    { id: 'Louisiana', body: 'Louisiana'} ,
    { id: 'Maine', body: 'Maine'} ,
    { id: 'Maryland', body: 'Maryland'} ,
    { id: 'Massachusetts', body: 'Massachusetts'} ,
    { id: 'Michigan', body: 'Michigan'} ,
    { id: 'Minnesota', body: 'Minnesota'} ,
    { id: 'Mississippi', body: 'Mississippi'} ,
    { id: 'Missouri', body: 'Missouri'} ,
    { id: 'Montana', body: 'Montana'} ,
    { id: 'Nebraska', body: 'Nebraska'} ,
    { id: 'Nevada', body: 'Nevada'} ,
    { id: 'New Hampshire', body: 'New Hampshire'} ,
    { id: 'New Jersey', body: 'New Jersey'} ,
    { id: 'New Mexico', body: 'New Mexico'} ,
    { id: 'New York', body: 'New York'} ,
    { id: 'North Carolina', body: 'North Carolina'} ,
    { id: 'North Dakota', body: 'North Dakota'} ,
    { id: 'Ohio', body: 'Ohio'} ,
    { id: 'Oklahoma', body: 'Oklahoma'} ,
    { id: 'Oregon', body: 'Oregon'} ,
    { id: 'Pennsylvania', body: 'Pennsylvania'} ,
    { id: 'Rhode Island', body: 'Rhode Island'} ,
    { id: 'South Carolina', body: 'South Carolina'} ,
    { id: 'South Dakota', body: 'South Dakota'} ,
    { id: 'Tennessee', body: 'Tennessee'} ,
    { id: 'Texas', body: 'Texas'} ,
    { id: 'Utah', body: 'Utah'} ,
    { id: 'Vermont', body: 'Vermont'} ,
    { id: 'Virginia', body: 'Virginia'} ,
    { id: 'Washington', body: 'Washington'} ,
    { id: 'West Virginia', body: 'West Virginia'} ,
    { id: 'Wisconsin', body: 'Wisconsin'} ,
    { id: 'Wyoming', body: 'Wyoming'}
] ;