import { NavController, NavParams } from 'ionic-angular';
import { Gesture, Platform } from 'ionic-angular';
import { Renderer } from '@angular/core';
import { ThemeableBrowserObject } from '@ionic-native/themeable-browser';
import { AppConfig } from '../../config/app.config';
import { TranslatorService } from '../../translator/translator.service';
export declare class PdfViewPage {
    translator: TranslatorService;
    appConfig: AppConfig;
    nav: NavController;
    navParams: NavParams;
    renderer: Renderer;
    platform: Platform;
    title: string;
    pdfPath: string;
    themeColor: string;
    zoomLevel: number;
    lastZoomLevel: number;
    loadingSpinner: boolean;
    velocity: number;
    elementParent: any;
    elementChild: any;
    gesture: Gesture;
    container: any;
    viewer: any;
    transforms: any[];
    initialScale: number;
    previousScale: number;
    adjustDeltaX: number;
    adjustDeltaY: number;
    offsetX: number;
    offsetY: number;
    pixelDensity: number;
    currentScale: any;
    currentZoom: number;
    currentDeltaX: any;
    currentDeltaY: any;
    browser: ThemeableBrowserObject;
    enableAndroidViewer: boolean;
    constructor(translator: TranslatorService, appConfig: AppConfig, nav: NavController, navParams: NavParams, renderer: Renderer, platform: Platform);
    ionViewDidLoad(): void;
    displayPDF(): void;
    rgb2hex(rgb: any): string;
    loadStart(resource: any, ref: any): void;
    loadStop(resource: any): void;
    loadError(resource: any): void;
    exit(resource: any, ref: any): void;
    error(error: any, logMsg: string): void;
    goBack(): void;
    loadComplete(): void;
    init: () => void;
    doZoom(ev: any): void;
    gestureEnd(ev: any): void;
}
